### ISSUE TITLE
aaxc format

### ISSUE THREAD

**Issue by antonellodamessina** [adrifcastr/OSAC#11]
OSAC doesn't processes aaxc format files.

**Comment by adrifcastr** [comment]
not sure if those work with rcrack. I'll look into it if I happen to encounter that file format.

**Comment by thw0rted** [comment]
If I understand correctly, the new format is specific to the phone app, so you get AAX with the desktop downloader and AAXC on the phone, if that helps.

**Comment by antonellodamessina** [comment]
> 
> 
> If I understand correctly, the new format is specific to the phone app, so you get AAX with the desktop downloader and AAXC on the phone, if that helps.

Yes, that's what I'm doing right now.
